apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: idp-ingress-route
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: "Host(`api.lucasji.cn`) && PathPrefix(`/idp`)"
      services:
        - kind: Service
          name: starry-idp-svc
          port: 8000
      middlewares:
        - name: idp-ingress-middleware
