apiVersion: v1
kind: Service
metadata:
  name: starry-idp-svc
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8080
      nodePort: 31000
  selector:
    app: starry-idp
