apiVersion: v1
kind: Service
metadata:
  name: minio-svc
spec:
  type: ClusterIP
  ports:
    - port: 9202
      name: minio-api
      targetPort: 9202
      protocol: TCP
    - port: 9201
      name: minio-console-address
      targetPort: 9201
      protocol: TCP
  selector:
    app: minio
