spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://postgres:5432/idp
redis:
  master:
    host: my-redis-master-0.my-redis-headless.default.svc.cluster.local
    port: 6379
  replicas:
    - host: my-redis-replicas-0.my-redis-headless.default.svc.cluster.local
      port: 6379
    - host: my-redis-replicas-1.my-redis-headless.default.svc.cluster.local
      port: 6379
    - host: my-redis-replicas-2.my-redis-headless.default.svc.cluster.local
      port: 6379
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
